name: ist_validator
description: "A simple package to validate."
version: 0.0.1
homepage: https://spee.dev

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0